### ISSUE TITLE
Pe, ada error!

### ISSUE THREAD

**Issue by hakushigou** [zealcordNation/baldguy-bot#1]
Katanya kalo ada users yang gak join gh-sposnsor maka error. di bagian 
`github : [users names]`  ada nama username yang gak terdaftar di gh sponsors.

**Comment by hakushigou** [comment]
menurut saya hapus aja dah github sponsors nya. `github : ` bagian itu. Katanya belum ada di Indonesia (github sponsors nya (Untuk username yang pingin jadi sponsor))

[sumber nya ini pak!](https://github.com/sponsors/)

**Comment by mozartrafi** [comment]
Hmmmmmm
